# Generated by Django 2.0.4 on 2018-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
