# Generated by Django 2.0.4 on 2018-04-08 11:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180408_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='categorie',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Forum1', 'Forum1'), ('Archive', 'archive')], default='Forum1', max_length=14),
            preserve_default=False,
        ),
    ]
