# Generated by Django 2.0.3 on 2018-04-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name_plural': 'cours'},
        ),
    ]
