# Generated by Django 2.0.3 on 2018-03-31 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cours',
            new_name='Chapitre',
        ),
    ]
