# Generated by Django 2.0.3 on 2018-03-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_auto_20180331_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='topic',
            field=models.CharField(max_length=500),
        ),
    ]
