# Generated by Django 2.0.3 on 2018-03-31 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_auto_20180331_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=5000)),
                ('Photo', models.FileField(upload_to='')),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='exercice',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Cours'),
        ),
        migrations.DeleteModel(
            name='Chapitre',
        ),
    ]
