# Generated by Django 2.0.3 on 2018-04-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_auto_20180403_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='videoId',
            new_name='video_id',
        ),
    ]
