# Generated by Django 2.0.3 on 2018-04-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
