# Generated by Django 2.0.3 on 2018-04-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_remove_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.CharField(default='par curiosité', max_length=30),
            preserve_default=False,
        ),
    ]
