# Generated by Django 2.0.3 on 2018-04-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_auto_20180405_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
