# Generated by Django 2.0.4 on 2018-04-08 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cours', '0010_profile_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodanswer', models.BooleanField(default=False)),
                ('proposition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('show_answer', models.BooleanField(default=False)),
                ('is_multiplechoice', models.BooleanField(default=False)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Exercice')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('choice', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cours.Choice')),
                ('answer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Question'),
        ),
    ]
