# Generated by Django 2.0.4 on 2018-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0011_auto_20180408_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ManyToManyField(to='cours.Profile'),
        ),
    ]
