# Generated by Django 2.0.4 on 2018-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0014_auto_20180408_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='reponse',
        ),
        migrations.AddField(
            model_name='question',
            name='reponse',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
