# Generated by Django 2.0.4 on 2018-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0015_auto_20180409_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='show_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='show_answer',
            field=models.BooleanField(default=False),
        ),
    ]
