# Generated by Django 2.0.4 on 2018-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0019_auto_20180513_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='solved_exercices',
            field=models.ManyToManyField(blank=True, null=True, to='cours.Exercice'),
        ),
    ]
