# Generated by Django 2.0.4 on 2018-05-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0021_auto_20180513_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='niveau_de_formation',
            field=models.CharField(blank=True, choices=[('blank', ' '), ('Doctorat', 'Doctorat'), ('Master', 'Master'), ('Diplome de 1er cycle', 'Diplome de 1er cycle'), ('Lycée', 'Lycée'), ('Collège', 'Collège'), ('Enseignement Primaire', 'Enseignement Primaire'), ('Education non formelle', 'Education non formelle'), ('Autre Education', 'Autre Education')], max_length=60, null=True),
        ),
    ]
