# Generated by Django 2.0.4 on 2018-05-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0022_auto_20180514_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('blank', ' '), ('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=60, null=True),
        ),
    ]
