# Generated by Django 2.0.4 on 2018-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0023_auto_20180514_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='solved_exercices',
            field=models.ManyToManyField(blank=True, to='cours.Exercice'),
        ),
    ]
